import { ThemeProvider } from "@/components/theme-provider"
import type { Metadata } from "next";
import { Geist } from "next/font/google";
import Footer from "@/components/ui/footer/Footer";
import NextTopLoader from "nextjs-toploader";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <NextTopLoader color="oklch(0.6892 0.2004 22.38)"  />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}
